baseURL: 'https://example.org/'
languageCode: 'en-us'
title: 'A platypus with a pen'
theme: [PaperMod]
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: 'Writing to a portaledge'
  description: "Sharanya writes about making it to various portaledges"
  keywords: [Blog, Portfolio]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["images/platypus.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: 'Writing to a portaledge'
    subtitle: A platypus with a pen.
    imageUrl: "images/platypus.png"
    imageWidth: 96
    imageHeight: 96
    imageTitle: platypus
    buttons:
      - name: Stuff I've written
        url: posts
      # - name: Tags
      #   url: tags

  # home-info mode
  homeInfoParams:
      Title: "Hi there \U0001F44B"
      Content: Welcome to my portaledge.
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 2
    - identifier: tags
      name: tags
      url: /tags/
      weight: 4
    - name: archive
      url: archives
      weight: 1
    - name: search
      url: search/
      weight: 3

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary